export const AppointmentStatus = Object.freeze({
  CONFIRMED: 'Confirmed',
  COMPLETED: 'Completed',
  CANCELLED: 'Cancelled',
  PENDING: 'Pending',
  IN_PROGRESS: 'In Progress',
});

export const AppointmentType = Object.freeze({
  VIDEO: 'Video Call',
  IN_PERSON: 'In-Person',
});


export const MOCK_DOCTORS = [
  {
    id: 'd1',
    name: 'Dr. Sarah Smith',
    specialty: 'General Physician',
    department: 'General Medicine',
    rating: 4.8,
    reviewsCount: 124,
    experience: 10,
    bio: 'Dr. Sarah Smith is a highly experienced general physician with a passion for student health and wellness.',
    education: ['MD - Harvard Medical School', 'Residency - Mayo Clinic'],
    image: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=200&h=200',
    nextAvailable: 'Tomorrow at 10:30 AM',
  },
  {
    id: 'd2',
    name: 'Dr. Michael Chen',
    specialty: 'Mental Health Counselor',
    department: 'Psychiatry',
    rating: 4.9,
    reviewsCount: 89,
    experience: 8,
    bio: 'Dr. Michael Chen specializes in student anxiety, stress management, and academic performance counseling.',
    education: ['PhD in Psychology - Stanford University'],
    image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200&h=200',
    nextAvailable: 'Today at 2:00 PM',
  },
  {
    id: 'd3',
    name: 'Dr. Emily Wilson',
    specialty: 'Dermatologist',
    department: 'Dermatology',
    rating: 4.7,
    reviewsCount: 56,
    experience: 6,
    bio: 'Dr. Emily Wilson provides comprehensive skin care treatments and consultations for students.',
    education: ['MD - Johns Hopkins University'],
    image: 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?auto=format&fit=crop&q=80&w=200&h=200',
    nextAvailable: 'Monday at 9:00 AM',
  },
];

export const MOCK_APPOINTMENTS = [
  {
    id: 'a1',
    doctorId: 'd1',
    doctorName: 'Dr. Sarah Smith',
    doctorSpecialty: 'General Physician',
    doctorImage: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=200&h=200',
    studentId: 's1',
    studentName: 'John Doe',
    date: '2026-03-05',
    time: '10:30 AM',
    type: AppointmentType.VIDEO,
    status: AppointmentStatus.CONFIRMED,
    meetingLink: 'https://meet.campushealth.edu/a1',
  },
  {
    id: 'a2',
    doctorId: 'd2',
    doctorName: 'Dr. Michael Chen',
    doctorSpecialty: 'Mental Health Counselor',
    doctorImage: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200&h=200',
    studentId: 's1',
    studentName: 'John Doe',
    date: '2026-02-20',
    time: '02:00 PM',
    type: AppointmentType.IN_PERSON,
    status: AppointmentStatus.COMPLETED,
    prescriptionId: 'p1',
  },
  {
    id: 'a3',
    doctorId: 'd1',
    doctorName: 'Dr. Sarah Smith',
    doctorSpecialty: 'General Physician',
    doctorImage: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=200&h=200',
    studentId: 's2',
    studentName: 'Jane Smith',
    date: '2026-03-05',
    time: '2:45 PM',
    type: AppointmentType.IN_PERSON,
    status: AppointmentStatus.CONFIRMED,
    meetingLink: 'https://meet.campushealth.edu/a3',
  },
  {
    id: 'a4',
    doctorId: 'd1',
    doctorName: 'Dr. Sarah Smith',
    doctorSpecialty: 'General Physician',
    doctorImage: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=200&h=200',
    studentId: 's3',
    studentName: 'Robert Brown',
    date: '2026-03-05',
    time: '3:00 PM',
    type: AppointmentType.VIDEO,
    status: AppointmentStatus.CONFIRMED,
    meetingLink: 'https://meet.campushealth.edu/a4',
  },
];

export const MOCK_PRESCRIPTIONS = [
  {
    id: 'p1',
    appointmentId: 'a2',
    doctorId: 'd2',
    doctorName: 'Dr. Michael Chen',
    studentId: 's1',
    date: '2026-02-20',
    medicines: [
      {
        name: 'Sertraline',
        dosage: '50mg',
        duration: '30 days',
        instructions: 'Take one tablet daily in the morning with food.',
      },
    ],
    notes: 'Follow up in 4 weeks.',
  },
];

export const MOCK_PATIENTS = [
  {
    id: 's1',
    name: 'John Doe',
    age: 21,
    gender: 'Male',
    bloodType: 'O+',
    allergies: ['Penicillin'],
    history: [
      { condition: 'Seasonal Allergies', date: '2024-05-10' },
      { condition: 'Mild Anxiety', date: '2025-01-15' },
    ],
    lastVisit: '2026-02-20',
  },
  {
    id: 's2',
    name: 'Jane Smith',
    age: 19,
    gender: 'Female',
    bloodType: 'A+',
    allergies: [],
    history: [],
    lastVisit: '2026-01-10',
  },
  {
    id: 's3',
    name: 'Robert Brown',
    age: 22,
    gender: 'Male',
    bloodType: 'B+',
    allergies: ['Sulfa'],
    history: [{ condition: 'Migraine', date: '2025-06-01' }],
    lastVisit: '2026-02-15',
  },
];
